version: "2"
exclude_patterns:
  - "config/"
  - "bootstrap/"
  - "database/"
  - "**/node_modules/"
  - "**/vendor/"
  - "**/tests/"
  - "**/__mocks__/"
  - "**/__tests__/"
  - "**/*.spec.php"
  - "app/**/Kernel.php"
  - "app/**/Handler.php"
  - "app/**/Controller.php"
  - "app/User.php"
  - "app/Http/Controllers/Auth/*.php"
  - "app/Http/Middleware/Authenticate.php"
  - "app/Http/Middleware/CheckForMaintenanceMode.php"
  - "app/Http/Middleware/EncryptCookies.php"
  - "app/Http/Middleware/RedirectIfAuthenticated.php"
  - "app/Http/Middleware/TrimStrings.php"
  - "app/Http/Middleware/TrustProxies.php"
  - "app/Http/Middleware/VerifyCsrfToken.php"
  - "app/Providers/AppServiceProvider.php"
  - "app/Providers/AuthServiceProvider.php"
  - "app/Providers/BroadcastServiceProvider.php"
  - "app/Providers/EventServiceProvider.php"
  - "app/Providers/RouteServiceProvider.php"
  - "resources/js/app.js"
  - "resources/js/bootstrap.js"
  - "resources/js/components/ExampleComponents.vue"
  - "resources/lang/en/auth.php"
  - "resources/lang/en/pagination.php"
  - "resources/lang/en/passwords.php"
  - "resources/lang/en/validation.php"
  - "resources/sass"
  - "resources/views/welcome.blade.php"
  - "storage/app/"
  - "storage/framework/"
  - "storage/logs/"
  - "public/css"
  - "public/svg"
  - "public/js/app.js"
  - "public/index.php"
  - "public/favicon.ico"
  - "public/*.txt"
  - "public/*.config"
